const products = [
  { id: 1, name: 'Aceite de oliva reserva', category: 'aceites', price: 12990, description: 'Extra virgen, cosecha temprana.', image: "url('https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=700&q=80')" },
  { id: 2, name: 'Miel de ulmo', category: 'dulces', price: 8490, description: 'Miel nativa de aroma floral.', image: "url('https://images.unsplash.com/photo-1587049352851-8d4e89133924?auto=format&fit=crop&w=700&q=80')" },
  { id: 3, name: 'Sal de Cahuil', category: 'sales', price: 5990, description: 'Cristales naturales de costa.', image: "url('https://images.unsplash.com/photo-1506368249639-73a05d6f6488?auto=format&fit=crop&w=700&q=80')" },
  { id: 4, name: 'Mermelada de higo', category: 'dulces', price: 7490, description: 'Receta artesanal, fruta real.', image: "url('https://images.unsplash.com/photo-1559181567-c3190ca9959b?auto=format&fit=crop&w=700&q=80')" },
  { id: 5, name: 'Aceite al merkén', category: 'aceites', price: 10990, description: 'Intenso, ahumado y envolvente.', image: "url('https://images.unsplash.com/photo-1474440692490-2e83ae13ba29?auto=format&fit=crop&w=700&q=80')" },
  { id: 6, name: 'Mix de especias', category: 'sales', price: 6790, description: 'Mezcla cálida para cada día.', image: "url('https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=700&q=80')" },
  { id: 7, name: 'Dulce de leche', category: 'dulces', price: 6990, description: 'Cremoso y de elaboración lenta.', image: "url('https://images.unsplash.com/photo-1614088685112-0a760b71a3a2?auto=format&fit=crop&w=700&q=80')" },
  { id: 8, name: 'Sal con hierbas', category: 'sales', price: 5490, description: 'Toque verde para terminar platos.', image: "url('https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=700&q=80')" }
];
const currency = value => new Intl.NumberFormat('es-CL', { style: 'currency', currency: 'CLP', maximumFractionDigits: 0 }).format(value);
let cart = [];
const grid = document.getElementById('productsGrid');
const panel = document.getElementById('cartPanel');
const overlay = document.getElementById('overlay');
function renderProducts(category = 'todos') { const visible = category === 'todos' ? products : products.filter(product => product.category === category); grid.innerHTML = visible.map(product => `<article class="product-card"><div class="product-image" style="--product-image:linear-gradient(rgba(36,52,40,.3),rgba(36,52,40,.62)), ${product.image}"><span>${product.category}</span></div><div class="product-body"><span class="product-category">${product.category}</span><h3>${product.name}</h3><p>${product.description}</p><div class="product-bottom"><strong>${currency(product.price)}</strong><button class="add-button" data-id="${product.id}" type="button">Agregar</button></div></div></article>`).join(''); }
function renderCart() { const items = document.getElementById('cartItems'); const total = cart.reduce((sum, item) => sum + item.price, 0); document.getElementById('cartCount').textContent = cart.length; document.getElementById('cartTotal').textContent = currency(total); items.innerHTML = cart.length ? cart.map((item, index) => `<article class="cart-item"><div><h3>${item.name}</h3><p>${item.category}</p></div><strong>${currency(item.price)}</strong><button class="remove-button" data-index="${index}" type="button">Quitar</button></article>`).join('') : '<p class="empty-cart">Tu carrito está vacío.</p>'; }
function toggleCart(show) { panel.classList.toggle('open', show); panel.setAttribute('aria-hidden', String(!show)); document.getElementById('cartButton').setAttribute('aria-expanded', String(show)); overlay.hidden = !show; }
document.querySelector('.filters').addEventListener('click', event => { const button = event.target.closest('.filter'); if (!button) return; document.querySelectorAll('.filter').forEach(item => item.classList.toggle('active', item === button)); renderProducts(button.dataset.category); });
grid.addEventListener('click', event => { const button = event.target.closest('.add-button'); if (!button) return; cart.push(products.find(product => product.id === Number(button.dataset.id))); renderCart(); toggleCart(true); });
document.getElementById('cartItems').addEventListener('click', event => { const button = event.target.closest('.remove-button'); if (!button) return; cart.splice(Number(button.dataset.index), 1); renderCart(); });
document.getElementById('cartButton').addEventListener('click', () => toggleCart(true)); document.getElementById('closeCart').addEventListener('click', () => toggleCart(false)); overlay.addEventListener('click', () => toggleCart(false));
document.getElementById('checkoutButton').addEventListener('click', () => { document.getElementById('cartMessage').textContent = cart.length ? 'Compra simulada correctamente. ¡Gracias por elegir GourmetShop!' : 'Agrega productos para continuar.'; if (cart.length) { cart = []; renderCart(); } });
renderProducts(); renderCart();
